### ISSUE TITLE
about evaluation setting？

### ISSUE THREAD

**Issue by DIVE128** [liuyuan-pal/LMCNet#4]
Hollow, thanks for your generous sharing.  And we are interested in your work and your brief code of evaluation framework. There’re two question about the evalution?
1. Is there any difference of RANSACEstimator and RescaleRANSACEstimator when evaluting the filter model?In readme.md, It uses rescale_ransac_1600 in yfcc and ransac_0.001 in sun3d while they'are both using sift to extract keypoints without rescaling .
2. We find the auc is entire lowering about 0.5%~1% with different methods (pretrained model, lmc,lmc-gemo,oanet...) in yfcc with setting: sift,nn,"method" rescale_ransac_1600 (using in readme.md)comparing with it in the paper,  is there any setting wrong in evalution?

**Comment by DIVE128** [comment]
issue 2 happens in sun3d with setting:sift ,nn, too.

**Comment by liuyuan-pal** [comment]
Hi, thanks for your interest.

1. The rescale RANSAC in this estimator rescales the coordinates only when estimating the geometry. 
https://github.com/liuyuan-pal/LMCNet/blob/37f1844550eab925be3291d64de11cf2fdbcea00/estimator.py#L73

This is actually the same as SuperGlue on YFCC dataset since they rescale the input image when detecting keypoints, but they do not scale the input image back afterward. I directly follow their setting to avoid parameter tuning on this.
2. The difference may be caused by the randomness of RANSAC. You can also try other RANSAC thresholds.

**Comment by DIVE128** [comment]
Thanks for your reply
